import type { NextPage } from "next";
import Head from "next/head";

import PostList from "~/components/PostList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gesundheit für dich</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center bg-gradient-to-b  text-gray-600">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Gesundheit für dich
          </h1>
          <div>
            <PostList />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
